# Form implementation generated from reading ui file 'image_display_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_image_display_widget(object):
    def setupUi(self, image_display_widget):
        image_display_widget.setObjectName("image_display_widget")
        image_display_widget.resize(646, 597)
        self.verticalLayout = QtWidgets.QVBoxLayout(image_display_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelImage = QtWidgets.QLabel(parent=image_display_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(0, 0))
        self.labelImage.setText("")
        self.labelImage.setScaledContents(False)
        self.labelImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelImage.setObjectName("labelImage")
        self.verticalLayout.addWidget(self.labelImage)

        self.retranslateUi(image_display_widget)
        QtCore.QMetaObject.connectSlotsByName(image_display_widget)

    def retranslateUi(self, image_display_widget):
        _translate = QtCore.QCoreApplication.translate
        image_display_widget.setWindowTitle(_translate("image_display_widget", "Form"))
