# Form implementation generated from reading ui file 'options_tab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OptionsTab(object):
    def setupUi(self, OptionsTab):
        OptionsTab.setObjectName("OptionsTab")
        OptionsTab.resize(843, 646)
        self.gridLayout_2 = QtWidgets.QGridLayout(OptionsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=OptionsTab)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditWorldOfGooInstallation = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditWorldOfGooInstallation.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditWorldOfGooInstallation.setReadOnly(True)
        self.lineEditWorldOfGooInstallation.setObjectName("lineEditWorldOfGooInstallation")
        self.gridLayout_3.addWidget(self.lineEditWorldOfGooInstallation, 0, 1, 1, 1)
        self.labelSteamDirectory = QtWidgets.QLabel(parent=self.frame)
        self.labelSteamDirectory.setObjectName("labelSteamDirectory")
        self.gridLayout_3.addWidget(self.labelSteamDirectory, 1, 0, 1, 1)
        self.lineEditSteamDirectory = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditSteamDirectory.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditSteamDirectory.setReadOnly(True)
        self.lineEditSteamDirectory.setObjectName("lineEditSteamDirectory")
        self.gridLayout_3.addWidget(self.lineEditSteamDirectory, 1, 1, 1, 1)
        self.labelWorldOfGooInstallation = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWorldOfGooInstallation.sizePolicy().hasHeightForWidth())
        self.labelWorldOfGooInstallation.setSizePolicy(sizePolicy)
        self.labelWorldOfGooInstallation.setObjectName("labelWorldOfGooInstallation")
        self.gridLayout_3.addWidget(self.labelWorldOfGooInstallation, 0, 0, 1, 1)
        self.buttonBrowseWorldOfGooInstallation = QtWidgets.QPushButton(parent=self.frame)
        self.buttonBrowseWorldOfGooInstallation.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonBrowseWorldOfGooInstallation.setObjectName("buttonBrowseWorldOfGooInstallation")
        self.gridLayout_3.addWidget(self.buttonBrowseWorldOfGooInstallation, 0, 2, 1, 1)
        self.buttonBrowseSteamDirectory = QtWidgets.QPushButton(parent=self.frame)
        self.buttonBrowseSteamDirectory.setObjectName("buttonBrowseSteamDirectory")
        self.gridLayout_3.addWidget(self.buttonBrowseSteamDirectory, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)

        self.retranslateUi(OptionsTab)
        QtCore.QMetaObject.connectSlotsByName(OptionsTab)

    def retranslateUi(self, OptionsTab):
        _translate = QtCore.QCoreApplication.translate
        OptionsTab.setWindowTitle(_translate("OptionsTab", "Form"))
        self.labelSteamDirectory.setText(_translate("OptionsTab", "Steam Directory: "))
        self.labelWorldOfGooInstallation.setText(_translate("OptionsTab", "World of Goo Installation:"))
        self.buttonBrowseWorldOfGooInstallation.setText(_translate("OptionsTab", "Browse..."))
        self.buttonBrowseSteamDirectory.setText(_translate("OptionsTab", "Browse..."))
